country: US
data_types:
- legislation
jurisdiction: US-AZ
language: en
name: Arizona Revised Statutes
schedule: quarterly
schema:
  key_fields:
  - name: _id
    required: true
    type: string
  - name: title_number
    required: false
    type: string
  - name: section_number
    required: false
    type: string
source_id: US/AZ-Legislation
url: https://www.azleg.gov/arstitle/
