auth:
  type: none
country: US
data_types:
- legislation
fetch:
  delay: 1.5
jurisdiction: US-SC
language: en
license: public_domain
name: South Carolina Code of Laws
schedule: monthly
schema:
  key_fields:
  - name: _id
    required: true
    type: string
  - name: title
    required: true
    type: string
  - name: date
    required: false
    type: date
  - name: text
    required: true
    type: string
  - name: section_number
    required: false
    type: string
  - name: chapter
    required: false
    type: string
source_id: US/SC-Legislation
url: https://www.scstatehouse.gov/code/statmast.php
