api:
  base_url: https://jurisprudencia.cc.gob.gt/coredataretriever/api/jurisprudencia/V1
  content_type: application/json
  method: POST
  page_size: 100
  pdf_base_url: https://jurisprudencia.cc.gob.gt/Sentencias
  rate_limit_seconds: 1.5
auth: none
country: GT
data_types:
- case_law
name: Guatemala Corte de Constitucionalidad
schema:
  key_fields:
  - name: id
    required: false
    type: string
  - name: expedientes
    required: false
    type: string
  - name: fechaSentencia
    required: false
    type: string
  - name: tipoExpediente
    required: false
    type: string
  - name: pdf
    required: false
    type: string
source_id: GT/CC
url: https://jurisprudencia.cc.gob.gt/
