api:
  base_url: https://sc.supremecourt.gov.az
  detail_endpoint: /decision-search/show/
  search_endpoint: /decision-search/
country: AZ
data_types:
- caselaw
name: Azerbaijan Supreme Court
rate_limit:
  requests_per_second: 0.5
schema:
  key_fields:
  - name: work_no
    required: false
    type: string
  - name: date
    required: false
    type: date
source_id: AZ/SupremeCourt
