country: US
data_types:
- case_law
language: en
name: US Board of Immigration Appeals Decisions
schedule: monthly
schema:
  key_fields:
  - name: _id
    required: true
    type: string
  - name: volume
    required: false
    type: string
  - name: decision_number
    required: false
    type: string
source_id: US/BIA
url: https://www.justice.gov/eoir/board-of-immigration-appeals-decisions
