auth:
  type: none
data_model:
  dedup_key:
  - _id
  update_strategy: append_only
rate_limit:
  burst: 3
  requests_per_second: 1
schema:
  key_fields:
  - name: decision_type
    required: false
    type: string
  - name: case_number
    required: false
    type: string
  - name: addressee
    required: false
    type: string
  - name: topic
    required: false
    type: string
  required_fields:
  - _id
  - _source
  - _type
  - _fetched_at
  - title
  - text
  - date
  - url
source:
  country: EE
  data_types:
  - doctrine
  id: EE/AKI
  language: et
  name: Andmekaitse Inspektsioon (Estonian Data Protection Authority)
  url: https://www.aki.ee
