country: US
data_types:
- legislation
jurisdiction: US-OH
language: en
name: Ohio Revised Code
schedule: quarterly
schema:
  key_fields:
  - name: _id
    required: true
    type: string
  - name: title_slug
    required: false
    type: string
  - name: section_number
    required: false
    type: string
source_id: US/OH-Legislation
url: https://codes.ohio.gov/
