schema:
  key_fields:
  - name: _id
    required: true
    type: string
  - name: title
    required: true
    type: string
  - name: text
    required: true
    type: string
  - name: date
    required: false
    type: date
  - name: url
    required: true
    type: string
  - name: section_id
    required: false
    type: string
  - name: title_number
    required: false
    type: string
  - name: jurisdiction
    required: false
    type: string
source:
  auth: none
  country: US
  data_types:
  - legislation
  id: US/GA-Legislation
  jurisdiction: US-GA
  language: en
  name: Official Code of Georgia Annotated (O.C.G.A.)
  schedule: monthly
  url: https://archive.org/details/gov.ga.ocga.2018
